// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villas.API.Data;

#nullable disable

namespace Villas.API.Migrations
{
    [DbContext(typeof(VillaDbContext))]
    [Migration("20260611160325_SeedVillaData")]
    partial class SeedVillaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villas.API.Models.Domain.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxurious villa with stunning ocean views and private beach access.",
                            ImageUrl = "https://static.vecteezy.com/system/resources/thumbnails/035/974/293/small_2x/ai-generated-luxury-home-exterior-and-pool-on-sunny-day-with-blue-sky-free-photo.jpg",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Rate = 500m,
                            Sqft = 2500
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Elegant villa with marble interiors and panoramic mountain views.",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.RpZHEyv0mnqtn6TdVjQNlwHaE7?pid=Api&P=0&h=180",
                            LastUpdatedAt = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Diamond Villa",
                            Occupancy = 8,
                            Rate = 750m,
                            Sqft = 3200
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Modern villa featuring an infinity pool and outdoor entertainment area.",
                            ImageUrl = "https://tse4.mm.bing.net/th/id/OIP.kct6TCUyMIKQzWa2uXBNBQHaE8?pid=Api&P=0&h=180",
                            Name = "Pool Villa",
                            Occupancy = 4,
                            Rate = 350m,
                            Sqft = 1800
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Premium villa with spa facilities and concierge services.",
                            ImageUrl = "https://tse1.mm.bing.net/th/id/OIP.Ebeiw1CrSAS7JNkOrthplAHaEu?pid=Api&P=0&h=180",
                            LastUpdatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luxury Villa",
                            Occupancy = 10,
                            Rate = 900m,
                            Sqft = 4000
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Charming villa surrounded by tropical gardens and nature.",
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.FkHSoEx_TOwMkABTf2IrlQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
                            LastUpdatedAt = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garden Villa",
                            Occupancy = 3,
                            Rate = 275m,
                            Sqft = 1500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
